apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout-frontend-{{ .Values.network }}
  namespace: lux-explorer
  labels:
    app: blockscout-frontend
    network: {{ .Values.network }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: blockscout-frontend
      network: {{ .Values.network }}
  template:
    metadata:
      labels:
        app: blockscout-frontend
        network: {{ .Values.network }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.images.frontend }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_HOST
              value: {{ .Values.apiDomain }}
            - name: NEXT_PUBLIC_API_PROTOCOL
              value: https
            - name: NEXT_PUBLIC_APP_HOST
              value: {{ .Values.frontendDomain }}
            - name: NEXT_PUBLIC_APP_PROTOCOL
              value: https
            - name: NEXT_PUBLIC_NETWORK_NAME
              value: {{ .Values.chainName | quote }}
            - name: NEXT_PUBLIC_NETWORK_SHORT_NAME
              value: {{ .Values.chainShortName }}
            - name: NEXT_PUBLIC_NETWORK_ID
              value: {{ .Values.chainId | quote }}
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_NAME
              value: {{ .Values.coinName }}
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL
              value: {{ .Values.coinSymbol }}
            - name: NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS
              value: "18"
            - name: NEXT_PUBLIC_IS_TESTNET
              value: {{ .Values.isTestnet | quote }}
            - name: NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL
              value: wss
            - name: NEXT_PUBLIC_HOMEPAGE_CHARTS
              value: '["daily_txs"]'
            - name: NEXT_PUBLIC_VISUALIZE_API_HOST
              value: "https://{{ .Values.frontendDomain }}/visualizer"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blockscout-frontend-{{ .Values.network }}
  namespace: lux-explorer
  labels:
    app: blockscout-frontend
    network: {{ .Values.network }}
spec:
  type: ClusterIP
  selector:
    app: blockscout-frontend
    network: {{ .Values.network }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
