apiVersion: lux.network/v1alpha1
kind: LuxNetwork
metadata:
  name: luxd
  namespace: lux-testnet
spec:
  networkId: 2
  validators: 5
  adoptExisting: true

  ports:
    http: 9640
    staking: 9641

  consensus:
    sybilProtectionEnabled: true

  chainTracking:
    trackAllChains: true
