apiVersion: v1
kind: Service
metadata:
  name: exchange
  namespace: lux-exchange
  labels:
    app: exchange
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: exchange
    component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-gateway
  namespace: lux-exchange
  labels:
    app: exchange
    component: gateway
spec:
  type: ClusterIP
  selector:
    app: exchange
    component: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
