apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.genesis.configMapName }}
  namespace: {{ .Values.networks[.Values.network].namespace }}
data:
  genesis.json: |
    {{- .Files.Get (printf "genesis/%s.json" .Values.network) | nindent 4 }}
